version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0 
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"

  tourguide:  
    image: python:3.12
    ports:  
      - "8501:8501"  
    depends_on:  
      - elasticsearch  
    environment:  
      - ELASTICSEARCH_HOST=elasticsearch:9200  

  grafana:
    build:
      context: .
      dockerfile: Dockerfile.grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./chat_log.csv:/var/lib/grafana/chat_log.csv:ro
      - ./grafana.ini:/etc/grafana/grafana.ini:ro



volumes:  
  grafana-storage:

