version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  app:
    build: .
    container_name: danang-chatbot
    ports:
      - "8501:8501"
      - "8888:8888"
    depends_on:
      - elasticsearch
    volumes:
      - .:/app

volumes:
  esdata:
